server:
  port: 80
spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 25016
      database: car
car-config:
  apply-info-url: https://apply.jtys.sz.gov.cn/apply/app/status/norm/person
  notice-info-url: http://xqctk.jtys.sz.gov.cn/gbl/

